import { createFileRoute } from "@tanstack/react-router";
import { CreditCard, LockKeyhole } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Workspace } from "@/features/core/workspace";
import { bookings } from "@/features/core/mock-data";
import { formatMoney } from "@/lib/format";
export const Route = createFileRoute("/payments")({ head: () => ({ meta: [{ title: "Payments — Cary Mission Control" }, { name: "description", content: "Cary payment ledger and payout status." }, { property: "og:title", content: "Payments — Cary Mission Control" }, { property: "og:description", content: "Cary payment ledger and payout status." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PaymentsPage });
function PaymentsPage() { return <Workspace title="Payments"><div className="flex items-end justify-between"><div><p className="micro-label">Money</p><h2 className="mt-1 text-2xl font-semibold">Payment ledger</h2></div><Button>Create payment link</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="panel p-4"><p className="micro-label">Held</p><p className="mt-2 font-mono text-2xl font-semibold">£1,486.00</p></div><div className="panel p-4"><p className="micro-label">Released today</p><p className="mt-2 font-mono text-2xl font-semibold">£867.00</p></div><div className="panel p-4"><p className="micro-label">Platform fees</p><p className="mt-2 font-mono text-2xl font-semibold">£56.00</p></div></div><div className="panel mt-6 overflow-hidden"><div className="divide-y divide-border">{bookings.filter((item) => item.total).map((booking) => <div className="flex flex-wrap items-center gap-4 p-5" key={booking.ref}><span className="grid size-9 place-items-center rounded-md bg-live-tint text-live-foreground"><CreditCard size={17} /></span><div className="flex-1"><p className="font-mono text-xs font-semibold">PAY-{booking.ref.slice(5)}A</p><p className="mt-1 text-sm">{booking.ref} · {booking.customer}</p></div><div><p className="micro-label">Customer total</p><p className="mt-1 font-mono text-sm font-semibold">{formatMoney(booking.total)}</p></div><div><p className="micro-label">Mover payout</p><p className="mt-1 font-mono text-sm font-semibold">{formatMoney(booking.total - 7)}</p></div><span className="status-live rounded-full border px-2 py-1 text-[10px] font-semibold"><LockKeyhole className="mr-1 inline size-3" />Held</span><Button asChild size="sm" variant="outline"><Link to="/payments/$id/refund" params={{ id: `PAY-${booking.ref.slice(5)}A` }}>Refund</Link></Button></div>)}</div></div></Workspace>; }
