import { createFileRoute, Link } from "@tanstack/react-router";
import { Calculator, MessageCircle, Plus, ReceiptText } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Workspace } from "@/features/core/workspace";
import { formatMoney } from "@/lib/format";

export const Route = createFileRoute("/quotes/new")({
  head: () => ({ meta: [{ title: "Quote tool — Cary Mission Control" }, { name: "description", content: "Manual mock quote calculator for Cary removals." }, { property: "og:title", content: "Quote tool — Cary Mission Control" }, { property: "og:description", content: "Manual mock quote calculator for Cary removals." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: QuoteTool,
});
function QuoteTool() {
  const [hours, setHours] = useState(2); const [movers, setMovers] = useState(2); const [stairs, setStairs] = useState(1); const [van, setVan] = useState("Luton van"); const [recorded, setRecorded] = useState(false);
  const base = van === "Luton van" ? 64 : 48; const labour = hours * movers * 22; const stairsCharge = stairs * 9; const payout = base + labour + stairsCharge; const total = payout + 7;
  return <Workspace title="Quote tool"><div className="mx-auto max-w-5xl"><p className="micro-label">Manual pricing · mock only</p><h2 className="mt-2 text-3xl font-semibold">Build a clear removal quote.</h2><p className="mt-2 text-sm text-muted-foreground">This records a mock quote only. No payment link or WhatsApp message is sent outside this workspace.</p><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="panel p-5"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Van<select value={van} onChange={(event) => setVan(event.target.value)} className="mt-2 h-10 w-full border border-input bg-background px-3 text-sm"><option>Luton van</option><option>Transit</option></select></label><label className="text-sm font-medium">Mover count<Input className="mt-2" type="number" min="1" value={movers} onChange={(event) => setMovers(Math.max(1, Number(event.target.value)))} /></label><label className="text-sm font-medium">Estimated hours<Input className="mt-2" type="number" min="1" value={hours} onChange={(event) => setHours(Math.max(1, Number(event.target.value)))} /></label><label className="text-sm font-medium">Stair flights<Input className="mt-2" type="number" min="0" value={stairs} onChange={(event) => setStairs(Math.max(0, Number(event.target.value)))} /></label></div><div className="mt-6 border-t border-border pt-5"><p className="text-sm font-semibold">Assumptions</p><p className="mt-2 text-sm text-muted-foreground">Base van, labour and stair handling are visible so operators can explain the quote without hidden fees.</p></div></section><aside className="panel p-5"><div className="flex items-center gap-2"><Calculator className="size-4 text-live-foreground" /><p className="text-sm font-semibold">Quote summary</p></div><div className="mt-5 space-y-3 border-y border-border py-4 text-sm"><Row label="Mover payout" value={formatMoney(payout)} /><Row label="Cary platform fee" value={formatMoney(7)} /><Row label="Customer price" value={formatMoney(total)} /></div><Button className="mt-5 w-full" onClick={() => setRecorded(true)}><ReceiptText />Record mock quote</Button><Button asChild variant="outline" className="mt-2 w-full"><Link to="/bookings"><Plus />Apply to booking</Link></Button>{recorded ? <p role="status" className="mt-4 border border-live/30 bg-live-tint p-3 text-xs text-live-foreground">Mock quote recorded in this session. Customer messaging and payment links are intentionally not connected.</p> : null}</aside></div></div></Workspace>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between"><span className="text-muted-foreground">{label}</span><strong className="font-mono">{value}</strong></div>; }
