import { createFileRoute } from "@tanstack/react-router";
import { Activity, PauseCircle, PlayCircle } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useOperations } from "@/features/core/operations-store";
import { Workspace } from "@/features/core/workspace";
export const Route = createFileRoute("/system")({ head: () => ({ meta: [{ title: "System — Cary Mission Control" }, { name: "description", content: "Mock operational systems health and Scout controls." }, { property: "og:title", content: "System — Cary Mission Control" }, { property: "og:description", content: "Mock operational systems health and Scout controls." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: System });
function System() { const { scoutPaused, toggleScoutPaused, audit } = useOperations(); const [word, setWord] = useState(""); return <Workspace title="System"><div className="mx-auto max-w-4xl"><p className="micro-label">Mock systems</p><h2 className="mt-2 text-3xl font-semibold">Operational health.</h2><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["WhatsApp templates", "Mock library ready"], ["Reminder queue", "Mock queue healthy"], ["Payments", "Mock ledger only"]].map(([title, status]) => <div className="panel p-4" key={title}><Activity className="size-4 text-live-foreground" /><p className="mt-3 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{status}</p></div>)}</div><section className="panel mt-6 p-5"><p className="micro-label">Emergency Scout control</p><h3 className="mt-2 text-lg font-semibold">{scoutPaused ? "Scout is paused" : "Scout is active"}</h3><p className="mt-2 text-sm text-muted-foreground">This only changes mock dashboard state. No external messages or automations exist.</p>{!scoutPaused ? <div className="mt-4 max-w-sm"><label className="text-sm font-medium">Type PAUSE ALL to stop mock Scout activity<Input className="mt-2" value={word} onInput={(event) => setWord(event.currentTarget.value.toUpperCase())} /></label><Button className="mt-3" onClick={() => { if (word.trim() !== "PAUSE ALL") return; toggleScoutPaused(); setWord(""); }}><PauseCircle />Pause all</Button></div> : <Button className="mt-4" onClick={toggleScoutPaused}><PlayCircle />Resume mock Scout</Button>}</section><section className="panel mt-6 p-5"><p className="micro-label">Mock audit log</p><div className="mt-4 space-y-3">{audit.length ? audit.slice(0, 8).map((event) => <div key={event.id} className="border-b border-border pb-3 last:border-0"><p className="text-sm font-semibold">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{event.detail}</p></div>) : <p className="text-sm text-muted-foreground">Mock operator actions will appear here.</p>}</div></section></div></Workspace>; }
