import { ArrowLeft, Bot, Check, CheckCheck, ChevronDown, FileText, Paperclip, PauseCircle, Send, UserRound, X, Zap } from "lucide-react";
import { FormEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Conversation, bookings, movers } from "@/features/core/mock-data";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/features/core/status-badge";
import { useOperations } from "@/features/core/operations-store";
import { formatLondon } from "@/lib/time";
import { approvedTemplates, renderTemplate } from "./operations-catalog";

export function ChatView({ conversation, fullScreen = false, onAssignMover, onContextPanelChange, quickReplyRequest }: { conversation: Conversation; fullScreen?: boolean; onAssignMover?: () => void; onContextPanelChange?: (panel: "details" | "quickReplies" | "scoutTools") => void; quickReplyRequest?: { id: number; body: string } | null }) {
  const navigate = useNavigate();
  const { messages, sendMessage, sendTemplate, setTakeover, markRead } = useOperations();
  const [message, setMessage] = useState(""); const [templatePicker, setTemplatePicker] = useState(false); const [templateQuery, setTemplateQuery] = useState(""); const [selectedTemplateId, setSelectedTemplateId] = useState("booking_confirmed"); const [handover, setHandover] = useState(false); const [note, setNote] = useState(""); const [attachment, setAttachment] = useState(""); const [parameters, setParameters] = useState<Record<string, string>>({});
  const inputRef = useRef<HTMLTextAreaElement>(null); const endRef = useRef<HTMLDivElement>(null); const closed = conversation.window === "closed";
  const thread = messages[conversation.id] ?? [];
  const booking = bookings.find((item) => item.customerId === conversation.contactId || item.moverId === conversation.contactId);
  const mover = conversation.role === "Mover" ? movers.find((item) => item.id === conversation.contactId) : undefined;
  const takeover = conversation.takeover;
  const matchingTemplates = approvedTemplates.filter((template) => template.name.toLowerCase().includes(templateQuery.toLowerCase()) && (template.target === conversation.role || template.target === "Admin Ops"));
  const selectedTemplate = approvedTemplates.find((template) => template.id === selectedTemplateId) ?? matchingTemplates[0] ?? approvedTemplates[0];
  const defaults = useMemo(() => templateDefaults(conversation, booking, mover), [booking, conversation, mover]);
  const values = selectedTemplate ? { ...defaults, ...parameters } : {};
  const templateBody = selectedTemplate ? renderTemplate(selectedTemplate, values) : "";
  const templateReady = selectedTemplate ? selectedTemplate.parameters.every((parameter) => values[parameter.key]?.trim()) : false;

  useEffect(() => { markRead(conversation.id); endRef.current?.scrollIntoView({ block: "end" }); inputRef.current?.focus(); }, [conversation.id, markRead, thread.length]);
  useEffect(() => { setParameters({}); setSelectedTemplateId(conversation.role === "Mover" ? "job_assigned_mover" : "quote_ready_alert"); }, [conversation.id, conversation.role]);
  useEffect(() => { if (quickReplyRequest) { setMessage(quickReplyRequest.body); inputRef.current?.focus(); } }, [quickReplyRequest]);
  function send(event?: FormEvent<HTMLFormElement>) { event?.preventDefault(); if (closed) { setTemplatePicker(true); return; } sendMessage(conversation.id, message, attachment || undefined); setMessage(""); setAttachment(""); inputRef.current?.focus(); }
  function handleComposerKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }
  function chooseTemplate(id: string) { setSelectedTemplateId(id); setParameters({}); }

  return <section className={`relative flex min-h-0 flex-1 flex-col bg-card ${fullScreen ? "h-[100svh] min-h-0" : ""}`}>
    <header className="border-b border-border bg-card"><div className="flex min-h-16 items-center justify-between gap-3 px-3 sm:px-4"><div className="flex min-w-0 items-center gap-2 sm:gap-3">{fullScreen && <Button variant="ghost" size="icon" aria-label="Back to inbox" onClick={() => void navigate({ to: "/inbox" })}><ArrowLeft /></Button>}<span className="grid size-9 shrink-0 place-items-center rounded-full bg-muted text-xs font-bold text-muted-foreground">{conversation.name.split(" ").map((name) => name[0]).join("")}</span><div className="min-w-0"><Link to={conversation.role === "Mover" ? "/movers/$id" : "/customers/$id"} params={{ id: conversation.contactId }} className="block truncate text-sm font-semibold hover:underline">{conversation.name}</Link><div className="mt-0.5 flex items-center gap-1.5"><span className="text-xs text-muted-foreground">{conversation.role}</span><span className={closed ? "text-xs text-warning" : "text-xs text-live-foreground"}>{closed ? "24h window closed" : "Window open · 8h 24m left"}</span></div></div></div><div className="flex shrink-0 items-center gap-2">{booking && onAssignMover && <Button variant="outline" size="sm" onClick={onAssignMover}>Assign mover</Button>}<Button variant={takeover ? "default" : "outline"} size="sm" onClick={() => { if (takeover) setTakeover(conversation.id, false, ""); else setHandover(true); }}><PauseCircle size={15} />{takeover ? "Resume Scout" : "Take over"}</Button></div></div>{!takeover && <div className="flex items-center justify-between gap-2 border-t border-border bg-live-tint px-4 py-2 text-xs text-live-foreground"><span className="flex items-center gap-1.5"><Bot size={14} />Scout auto-pilot active</span><span className="hidden sm:inline">Human replies will pause Scout.</span></div>}</header>
    {handover && <div className="border-b border-border bg-muted p-3"><label className="block text-xs font-semibold">Handover note<Textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 min-h-20" placeholder="What should the next operator know?" /></label><div className="mt-2 flex gap-2"><Button size="sm" disabled={!note.trim()} onClick={() => { setTakeover(conversation.id, true, note); setHandover(false); setNote(""); }}>Confirm takeover</Button><Button size="sm" variant="outline" onClick={() => setHandover(false)}>Cancel</Button></div></div>}
    {takeover && <div className="flex items-center gap-2 border-b border-warning/30 bg-warning-tint px-4 py-2 text-xs text-warning"><StatusBadge status="operator" label="Human takeover" /><span>Scout is paused while Amelia replies.</span></div>}
    <div className="flex-1 space-y-4 overflow-y-auto bg-muted/40 p-4 sm:p-5"><div className="text-center"><span className="border border-border bg-card px-2 py-1 text-[10px] text-muted-foreground">Today, London time</span></div>{thread.map((item) => { const agentMessage = item.sender === "scout"; const operatorMessage = item.sender === "operator"; const own = agentMessage || operatorMessage; return <div key={item.id} className={`${own ? "ml-auto" : ""} max-w-[92%] sm:max-w-[78%]`}><div className={`${agentMessage ? "bg-live-tint" : operatorMessage ? "bg-accent" : "bg-card"} border border-border p-3 text-sm`}><div className={`mb-1 flex items-center gap-1 text-[10px] text-muted-foreground ${own ? "justify-end" : ""}`}>{agentMessage ? <Bot size={11} /> : operatorMessage ? <UserRound size={11} /> : null}<span>{operatorMessage ? "Amelia · Operator" : agentMessage ? "Scout · AI" : conversation.name}{item.templateName ? ` · ${item.templateName}` : ""}</span></div><p className="whitespace-pre-wrap">{item.body}</p>{item.mediaName && <div className="mt-2 flex items-center gap-2 border-t border-border pt-2 text-xs text-muted-foreground"><FileText size={14} />Attachment: {item.mediaName}</div>}<p className="mt-1 text-right text-[10px] text-muted-foreground">{formatMessageTime(item.createdAt)} {own && (item.delivery === "sent" ? <Check className="inline size-3" /> : <CheckCheck className="inline size-3 text-live-foreground" />)}</p></div></div>; })}<div ref={endRef} /></div>
    <form onSubmit={send} className="sticky bottom-0 border-t border-border bg-card p-3 sm:p-4">{closed ? <div className="border border-warning/30 bg-warning-tint p-3"><p className="text-xs text-warning">24h window closed. Send an approved template instead.</p><Button type="button" variant="outline" size="sm" className="mt-2" onClick={() => setTemplatePicker(true)}>Choose approved template <ChevronDown size={14} /></Button></div> : <><div className="relative flex items-end gap-2"><input id={`attachment-${conversation.id}`} type="file" className="sr-only" onChange={(event) => setAttachment(event.target.files?.[0]?.name ?? "")} /><label htmlFor={`attachment-${conversation.id}`}><Button type="button" variant="ghost" size="icon" aria-label="Attach file" asChild><span><Paperclip /></span></Button></label><Textarea ref={inputRef} value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={handleComposerKeyDown} placeholder="Message as Amelia…" className="min-h-10 max-h-28 resize-none py-2" rows={1} /><Button type="submit" size="icon" aria-label="Send message" disabled={!message.trim() && !attachment}><Send /></Button></div><div className="mt-2 flex flex-wrap items-center gap-2"><Button type="button" variant="ghost" size="sm" onClick={() => onContextPanelChange?.("quickReplies")}><Zap size={14} />Quick replies</Button><Button type="button" variant="ghost" size="sm" onClick={() => setTemplatePicker(true)}><FileText size={14} />Templates</Button><Button type="button" variant="ghost" size="sm" onClick={() => onContextPanelChange?.("scoutTools")}>Scout tools</Button><span className="text-[10px] text-muted-foreground">Enter to send · Shift+Enter for a new line</span></div>{attachment && <div className="mt-2 flex items-center justify-between border border-border bg-muted px-2 py-1 text-xs"><span className="truncate">{attachment}</span><Button type="button" size="icon" variant="ghost" aria-label="Remove attachment" onClick={() => setAttachment("")}><X /></Button></div>}</>}</form>
    {templatePicker && selectedTemplate && <div className="absolute inset-0 z-20 flex justify-end bg-foreground/10" role="dialog" aria-label="Approved WhatsApp templates"><section className="flex h-full w-full max-w-md flex-col border-l border-border bg-card shadow-lg"><div className="flex items-center justify-between border-b border-border p-4"><div><p className="text-sm font-semibold">Approved templates</p><p className="mt-0.5 text-xs text-muted-foreground">Required when the 24-hour window is closed</p></div><Button type="button" variant="ghost" size="icon" aria-label="Close templates" onClick={() => setTemplatePicker(false)}><X /></Button></div><div className="min-h-0 flex-1 overflow-y-auto p-4"><label className="micro-label" htmlFor={`template-search-${conversation.id}`}>Search library</label><input id={`template-search-${conversation.id}`} value={templateQuery} onChange={(event) => setTemplateQuery(event.target.value)} placeholder="Search templates" className="mt-2 h-9 w-full border border-input bg-card px-3 text-sm" /><div className="mt-3 grid gap-1">{matchingTemplates.map((template) => <Button key={template.id} type="button" variant={template.id === selectedTemplate.id ? "secondary" : "ghost"} className="justify-start" onClick={() => chooseTemplate(template.id)}>{template.name}</Button>)}{!matchingTemplates.length && <p className="p-2 text-xs text-muted-foreground">No approved template matches this conversation.</p>}</div><div className="mt-5 border border-border bg-muted/40 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-semibold">{selectedTemplate.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{selectedTemplate.category} · {selectedTemplate.target} · English (UK)</p></div><StatusBadge status="approved" label="Approved" /></div><div className="mt-3 grid gap-2">{selectedTemplate.parameters.map((parameter) => <label className="text-xs font-medium" key={parameter.key}>{`{{${parameter.key}}}`} · {parameter.label}<input className="mt-1 h-8 w-full border border-input bg-card px-2 text-sm" value={values[parameter.key] ?? ""} onChange={(event) => setParameters((current) => ({ ...current, [parameter.key]: event.target.value }))} /></label>)}</div><div className="mt-3 border border-border bg-card p-3"><p className="micro-label">WhatsApp preview</p><p className="mt-2 whitespace-pre-wrap text-sm">{templateBody}</p></div></div></div><div className="border-t border-border p-4"><Button disabled={!templateReady} type="button" className="w-full" onClick={() => { sendTemplate(conversation.id, selectedTemplate.name, templateBody); setTemplatePicker(false); }}>Send approved template</Button></div></section></div>}
  </section>;
}

function templateDefaults(conversation: Conversation, booking: typeof bookings[number] | undefined, mover: typeof movers[number] | undefined): Record<string, string> {
  const parts = booking?.route.split(" → ") ?? []; const pickup = parts[0] ?? ""; const dropoff = parts[1] ?? ""; const moveTime = booking ? formatLondon(booking.moveAt) : ""; const customer = booking?.customer ?? (conversation.role === "Customer" ? conversation.name : ""); const customerPhone = "Customer phone available to operators";
  return { "1": conversation.role === "Mover" ? (mover?.businessName ?? conversation.name) : customer.split(" ")[0] ?? "", "2": booking?.ref ?? "", "3": pickup, "4": dropoff, "5": moveTime, "6": booking?.items ?? "", "7": "Driver + 1 helper", "8": "Access details confirmed in booking", "9": "", };
}
function formatMessageTime(timestamp: string) { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(timestamp)); }