import { ArrowLeft, Bot, CheckCheck, Paperclip, Send, UserRound, X } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Conversation } from "@/features/core/mock-data";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/features/core/status-badge";
import { useOperations } from "@/features/core/operations-store";

export function ChatView({ conversation, fullScreen = false }: { conversation: Conversation; fullScreen?: boolean }) {
  const navigate = useNavigate(); const { messages, sendMessage, sendTemplate, setTakeover, markRead } = useOperations();
  const [message, setMessage] = useState(""); const [templates, setTemplates] = useState(false); const [handover, setHandover] = useState(false); const [note, setNote] = useState(""); const [attachment, setAttachment] = useState("");
  const inputRef = useRef<HTMLInputElement>(null); const endRef = useRef<HTMLDivElement>(null); const closed = conversation.window === "closed";
  const thread = messages[conversation.id] ?? [];
  useEffect(() => { markRead(conversation.id); endRef.current?.scrollIntoView({ block: "end" }); }, [conversation.id, markRead, thread.length]);
  function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (closed) { setTemplates(true); return; } sendMessage(conversation.id, message, attachment || undefined); setMessage(""); setAttachment(""); inputRef.current?.focus(); }
  const takeover = conversation.takeover;
  return <section className={`flex min-h-0 flex-1 flex-col bg-card ${fullScreen ? "min-h-[calc(100svh-4rem)] pb-16 md:pb-0" : ""}`}>
    <header className="flex min-h-16 items-center justify-between border-b border-border px-3 sm:px-4">
      <div className="flex min-w-0 items-center gap-2 sm:gap-3">{fullScreen && <Button variant="ghost" size="icon" aria-label="Back to inbox" onClick={() => void navigate({ to: "/inbox" })}><ArrowLeft /></Button>}<span className="grid size-9 shrink-0 place-items-center rounded-full bg-muted text-xs font-bold text-muted-foreground">{conversation.name.split(" ").map((name) => name[0]).join("")}</span><div className="min-w-0"><Link to={conversation.role === "Mover" ? "/movers/$id" : "/customers/$id"} params={{ id: conversation.contactId }} className="block truncate text-sm font-semibold hover:underline">{conversation.name}</Link><div className="mt-0.5 flex items-center gap-1.5"><span className="text-xs text-muted-foreground">{conversation.role}</span><span className={closed ? "text-xs text-warning" : "text-xs text-live-foreground"}>{closed ? "24h window closed" : "Window open · 8h 24m left"}</span></div></div></div>
      <Button variant={takeover ? "default" : "outline"} size="sm" onClick={() => { if (takeover) setTakeover(conversation.id, false, ""); else setHandover(true); }}>{takeover ? "Resume Scout" : "Take over"}</Button>
    </header>
    {handover && <div className="border-b border-border bg-muted p-3"><label className="block text-xs font-semibold">Handover note<Input value={note} onChange={(event) => setNote(event.target.value)} className="mt-2" placeholder="What should the next operator know?" /></label><div className="mt-2 flex gap-2"><Button size="sm" disabled={!note.trim()} onClick={() => { setTakeover(conversation.id, true, note); setHandover(false); setNote(""); }}>Confirm takeover</Button><Button size="sm" variant="outline" onClick={() => setHandover(false)}>Cancel</Button></div></div>}
    {takeover && <div className="flex items-center gap-2 border-b border-border bg-muted px-4 py-2 text-xs"><StatusBadge status="operator" label="Operator" /><span className="text-muted-foreground">Scout is paused while an operator replies.</span></div>}
    <div className="flex-1 space-y-4 overflow-y-auto bg-muted/40 p-4 sm:p-5"><div className="text-center"><span className="border border-border bg-card px-2 py-1 text-[10px] text-muted-foreground">Today, London time</span></div>{thread.map((item) => { const own = item.sender === "operator" || item.sender === "scout"; return <div key={item.id} className={`${own ? "ml-auto bg-muted" : "bg-card"} max-w-[88%] border border-border p-3 text-sm sm:max-w-[78%]`}><div className={`mb-1 flex items-center gap-1 text-[10px] text-muted-foreground ${own ? "justify-end" : ""}`}>{item.sender === "scout" ? <Bot size={11} /> : item.sender === "operator" ? <UserRound size={11} /> : null}<span>{item.sender === "operator" ? "Amelia" : item.sender === "scout" ? "Scout" : conversation.name}</span></div><p>{item.body}</p>{item.mediaName && <p className="mt-2 border-t border-border pt-2 text-xs text-muted-foreground">Attachment: {item.mediaName}</p>}<p className="mt-1 text-right text-[10px] text-muted-foreground">13:42 {own && <CheckCheck className="inline size-3" />}</p></div>; })}<div ref={endRef} /></div>
    <form onSubmit={send} className="sticky bottom-0 border-t border-border bg-card p-3 sm:p-4">{closed ? <div className="border border-warning/30 bg-warning-tint p-3"><p className="text-xs text-warning">24h window closed. Send an approved template instead.</p><Button type="button" variant="outline" size="sm" className="mt-2" onClick={() => setTemplates(!templates)}>Choose template</Button>{templates && <div className="mt-2 border border-border bg-card p-3 text-xs"><p className="font-semibold">Move availability update</p><p className="mt-1 text-muted-foreground">Hello {conversation.name.split(" ")[0]}, we are checking availability for your move.</p><Button size="sm" className="mt-3" onClick={() => { sendTemplate(conversation.id); setTemplates(false); }}>Send template</Button></div>}</div> : <><div className="flex items-center gap-2"><input id={`attachment-${conversation.id}`} type="file" className="sr-only" onChange={(event) => setAttachment(event.target.files?.[0]?.name ?? "")} /><label htmlFor={`attachment-${conversation.id}`}><Button type="button" variant="ghost" size="icon" aria-label="Attach file" asChild><span><Paperclip /></span></Button></label><Input ref={inputRef} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Message as Amelia…" className="h-10 min-w-0" /><Button type="submit" size="icon" aria-label="Send message" disabled={!message.trim() && !attachment}><Send /></Button></div>{attachment && <div className="mt-2 flex items-center justify-between border border-border bg-muted px-2 py-1 text-xs"><span className="truncate">{attachment}</span><Button type="button" size="icon" variant="ghost" aria-label="Remove attachment" onClick={() => setAttachment("")}><X /></Button></div>}</>}</form>
  </section>;
}
