/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as InboxRouteImport } from './routes/inbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attention': typeof AttentionRoute
  '/bookings': typeof BookingsRoute
  '/inbox': typeof InboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attention': typeof AttentionRoute
  '/bookings': typeof BookingsRoute
  '/inbox': typeof InboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attention': typeof AttentionRoute
  '/bookings': typeof BookingsRoute
  '/inbox': typeof InboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attention' | '/bookings' | '/inbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attention' | '/bookings' | '/inbox'
  id: '__root__' | '/' | '/attention' | '/bookings' | '/inbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttentionRoute: typeof AttentionRoute
  BookingsRoute: typeof BookingsRoute
  InboxRoute: typeof InboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttentionRoute: AttentionRoute,
  BookingsRoute: BookingsRoute,
  InboxRoute: InboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
